import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="ly-ds-bg-primary ly-ds-text-description ly-ds-font-sans">{children}</body>
    </html>
  );
}
